### ISSUE TITLE
OS X 10.11 El Capitan support

### ISSUE THREAD

**Issue by joemaller** [ideasonpurpose/ansible-playbooks#24]

**Comment by mikesac** [comment]
hi there, after upgrading MacOsX to ElCapitan i'm getting the following error by simply invoking ansible-playbook
```
Traceback (most recent call last):
  File "/usr/local/bin/ansible-playbook", line 309, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/usr/local/bin/ansible-playbook", line 71, in main
    help="set additional variables as key=value or YAML/JSON", default=[])
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/optparse.py", line 1021, in add_option
    self._check_conflict(option)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/optparse.py", line 996, in _check_conflict
    option)
optparse.OptionConflictError: option -e/--extra-vars: conflicting option string(s): -e, --extra-vars
```
I tried to unistall ansible, paramiko PyYAML jinja2 and reinstall them via pip without using sudo but with the --user flag as suggested with the new Apple security system but nothing changed.

The same procedure seems to be succesful on another Mac with same Os version.
can you please provide any hint?

**Comment by joemaller** [comment]
I haven't had that problem yet, but it sounds like it's the Ansible installation (or Python).

**Comment by joemaller** [comment]
I should clarify. I've been running these playbooks from El Capitan for a few months, but most of my target machines are still on Yosemite. For convenience, I install Ansible (and Python 2 & 3) on the controller with Homebrew. 

But reading your error again, it looks like there's a problem with the `extra-vars` flag. These were written to do nothing without specifying a target in `extra-vars`, but they should just skip everything, not error. What was the actual command you're running to get that error? I'd also double-check which binaries are being called and what versions are running.

**Comment by mikesac** [comment]
actually I get the same error even invoking ansible-playbook alone:
```
~  ansible-playbook
Traceback (most recent call last):
  File "/usr/local/bin/ansible-playbook", line 309, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/usr/local/bin/ansible-playbook", line 71, in main
    help="set additional variables as key=value or YAML/JSON", default=[])
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/optparse.py", line 1021, in add_option
    self._check_conflict(option)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/optparse.py", line 996, in _check_conflict
    option)
optparse.OptionConflictError: option -e/--extra-vars: conflicting option string(s): -e, --extra-vars
```

**Comment by joemaller** [comment]
Working on El Cap.
